// <auto-generated />
using System;
using Pilllar.Vocal.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Pilllar.Vocal.Api.Migrations
{
    [DbContext(typeof(PilllarContext))]
    [Migration("20200522095632_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Pilllar.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6b322ea-6b72-45c0-8913-faa770115953"),
                            Email = "zeus@gmailcom",
                            Name = "Zeus",
                            Password = "$2$10$sL6A0FTqeDA8F4tjYkj3Fupcd4q6NrjabEq1CH8WyirRJNIfNEAxa",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = new Guid("68ae7e00-a5f5-4821-b921-a6cf80ff1623"),
                            Email = "atena@teste.com",
                            Name = "Atena",
                            Password = "$2$10$sL6A0FTqeDA8F4tjYkj3Fupcd4q6NrjabEq1CH8WyirRJNIfNEAxa",
                            Role = "Employee"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
